{"uid":"a356b369a5cced64","name":"title:搜索好友","fullName":"testcases.test_home_search.Test_home_search#test_home_search_friend","historyId":"3817102cf6d28efcf71a1963b978e97c","time":{"start":1702886410773,"stop":1702886412136,"duration":1363},"status":"broken","statusMessage":"packaging.version.InvalidVersion: Invalid version: ''","statusTrace":"self = <uiautomator2.Device object at 0x000001E5F1072450>\nargs = ('dumpWindowHierarchy', (False, None), 60), kwargs = {}\n\n    def _jsonrpc_retry_call(self, *args, **kwargs):\n        try:\n>           return self._jsonrpc_call(*args, **kwargs)\n\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:486: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <uiautomator2.Device object at 0x000001E5F1072450>\nmethod = 'dumpWindowHierarchy', params = (False, None), http_timeout = 60\n\n    def _jsonrpc_call(self, method, params=[], http_timeout=60):\n        \"\"\" jsonrpc2 call\n        Refs:\n            - http://www.jsonrpc.org/specification\n    \n        Raises:\n            出现的错误一般有2大类: 正常的请求错误 和 服务端异常\n            这里的代码主要是将这两大类错误正常归类\n        \"\"\"\n        request_start = time.time()\n        data = {\n            \"jsonrpc\": \"2.0\",\n            \"id\": self._jsonrpc_id(method),\n            \"method\": method,\n            \"params\": params,\n        }\n        data = json.dumps(data)\n        res = self.http.post(\"/jsonrpc/0\",\n                             headers={\"Content-Type\": \"application/json\"},\n                             data=data,\n                             timeout=http_timeout)\n    \n        if res.status_code == 502:\n>           raise GatewayError(\n                res, \"gateway error, time used %.1fs\" %\n                (time.time() - request_start))\nE           uiautomator2.exceptions.GatewayError: (<Response [502]>, 'gateway error, time used 0.1s')\n\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:519: GatewayError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <CompanyProject.APP_Forexchat.testcases.test_home_search.Test_home_search object at 0x000001E5F1204350>\n\n    @pytest.mark.run(order=2)\n    @allure.title('title:搜索好友')\n    def test_home_search_friend(self):\n        text = '好友'\n        with allure.step('点击找好友'):\n>           home_search().click_searchBox_out()\n\ntest_home_search.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\operation\\home\\home_search.py:13: in click_searchBox_out\n    self.searchBox_out.click()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:595: in click\n    el = self.get(timeout=timeout)\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:523: in get\n    if not self.wait(timeout or self._global_timeout):\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:559: in wait\n    if self.exists:\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:508: in exists\n    return len(self.all()) > 0\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:449: in all\n    xml_content = source or self._source or self._parent.dump_hierarchy()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:178: in dump_hierarchy\n    self._last_source = self._d.dump_hierarchy()\nC:\\Python311\\Lib\\site-packages\\decorator.py:232: in fun\n    return caller(func, *(extras + args), **kw)\nC:\\Python311\\Lib\\site-packages\\retry\\api.py:73: in retry_decorator\n    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,\nC:\\Python311\\Lib\\site-packages\\retry\\api.py:33: in __retry_internal\n    return f()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:978: in dump_hierarchy\n    content = self.jsonrpc.dumpWindowHierarchy(compressed, None)\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:479: in __call__\n    return self.server._jsonrpc_retry_call(self.method, params,\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:488: in _jsonrpc_retry_call\n    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:640: in reset_uiautomator\n    ok = self._force_reset_uiautomator_v2(\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:667: in _force_reset_uiautomator_v2\n    if self._is_apk_required():\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:711: in _is_apk_required\n    if self._package_version(\"com.github.uiautomator.test\") is None:\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:735: in _package_version\n    return packaging.version.parse(m.group('name') if m else \"\")\nC:\\Python311\\Lib\\site-packages\\packaging\\version.py:54: in parse\n    return Version(version)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <[AttributeError(\"'Version' object has no attribute '_version'\") raised in repr()] Version object at 0x1e5f1326290>\nversion = ''\n\n    def __init__(self, version: str) -> None:\n        \"\"\"Initialize a Version object.\n    \n        :param version:\n            The string representation of a version which will be parsed and normalized\n            before use.\n        :raises InvalidVersion:\n            If the ``version`` does not conform to PEP 440 in any way then this\n            exception will be raised.\n        \"\"\"\n    \n        # Validate the version and parse it into pieces\n        match = self._regex.search(version)\n        if not match:\n>           raise InvalidVersion(f\"Invalid version: '{version}'\")\nE           packaging.version.InvalidVersion: Invalid version: ''\n\nC:\\Python311\\Lib\\site-packages\\packaging\\version.py:200: InvalidVersion","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_class_fixture_Test_home_search","time":{"start":1702886400606,"stop":1702886407453,"duration":6847},"status":"passed","steps":[{"name":"step：打开应用","time":{"start":1702886400606,"stop":1702886407453,"duration":6847},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":1,"hasContent":true},{"name":"_xunit_setup_method_fixture_Test_home_search","time":{"start":1702886410772,"stop":1702886410772,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"packaging.version.InvalidVersion: Invalid version: ''","statusTrace":"self = <uiautomator2.Device object at 0x000001E5F1072450>\nargs = ('dumpWindowHierarchy', (False, None), 60), kwargs = {}\n\n    def _jsonrpc_retry_call(self, *args, **kwargs):\n        try:\n>           return self._jsonrpc_call(*args, **kwargs)\n\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:486: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <uiautomator2.Device object at 0x000001E5F1072450>\nmethod = 'dumpWindowHierarchy', params = (False, None), http_timeout = 60\n\n    def _jsonrpc_call(self, method, params=[], http_timeout=60):\n        \"\"\" jsonrpc2 call\n        Refs:\n            - http://www.jsonrpc.org/specification\n    \n        Raises:\n            出现的错误一般有2大类: 正常的请求错误 和 服务端异常\n            这里的代码主要是将这两大类错误正常归类\n        \"\"\"\n        request_start = time.time()\n        data = {\n            \"jsonrpc\": \"2.0\",\n            \"id\": self._jsonrpc_id(method),\n            \"method\": method,\n            \"params\": params,\n        }\n        data = json.dumps(data)\n        res = self.http.post(\"/jsonrpc/0\",\n                             headers={\"Content-Type\": \"application/json\"},\n                             data=data,\n                             timeout=http_timeout)\n    \n        if res.status_code == 502:\n>           raise GatewayError(\n                res, \"gateway error, time used %.1fs\" %\n                (time.time() - request_start))\nE           uiautomator2.exceptions.GatewayError: (<Response [502]>, 'gateway error, time used 0.1s')\n\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:519: GatewayError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <CompanyProject.APP_Forexchat.testcases.test_home_search.Test_home_search object at 0x000001E5F1204350>\n\n    @pytest.mark.run(order=2)\n    @allure.title('title:搜索好友')\n    def test_home_search_friend(self):\n        text = '好友'\n        with allure.step('点击找好友'):\n>           home_search().click_searchBox_out()\n\ntest_home_search.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\operation\\home\\home_search.py:13: in click_searchBox_out\n    self.searchBox_out.click()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:595: in click\n    el = self.get(timeout=timeout)\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:523: in get\n    if not self.wait(timeout or self._global_timeout):\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:559: in wait\n    if self.exists:\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:508: in exists\n    return len(self.all()) > 0\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:449: in all\n    xml_content = source or self._source or self._parent.dump_hierarchy()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py:178: in dump_hierarchy\n    self._last_source = self._d.dump_hierarchy()\nC:\\Python311\\Lib\\site-packages\\decorator.py:232: in fun\n    return caller(func, *(extras + args), **kw)\nC:\\Python311\\Lib\\site-packages\\retry\\api.py:73: in retry_decorator\n    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,\nC:\\Python311\\Lib\\site-packages\\retry\\api.py:33: in __retry_internal\n    return f()\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:978: in dump_hierarchy\n    content = self.jsonrpc.dumpWindowHierarchy(compressed, None)\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:479: in __call__\n    return self.server._jsonrpc_retry_call(self.method, params,\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:488: in _jsonrpc_retry_call\n    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:640: in reset_uiautomator\n    ok = self._force_reset_uiautomator_v2(\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:667: in _force_reset_uiautomator_v2\n    if self._is_apk_required():\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:711: in _is_apk_required\n    if self._package_version(\"com.github.uiautomator.test\") is None:\nC:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py:735: in _package_version\n    return packaging.version.parse(m.group('name') if m else \"\")\nC:\\Python311\\Lib\\site-packages\\packaging\\version.py:54: in parse\n    return Version(version)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <[AttributeError(\"'Version' object has no attribute '_version'\") raised in repr()] Version object at 0x1e5f1326290>\nversion = ''\n\n    def __init__(self, version: str) -> None:\n        \"\"\"Initialize a Version object.\n    \n        :param version:\n            The string representation of a version which will be parsed and normalized\n            before use.\n        :raises InvalidVersion:\n            If the ``version`` does not conform to PEP 440 in any way then this\n            exception will be raised.\n        \"\"\"\n    \n        # Validate the version and parse it into pieces\n        match = self._regex.search(version)\n        if not match:\n>           raise InvalidVersion(f\"Invalid version: '{version}'\")\nE           packaging.version.InvalidVersion: Invalid version: ''\n\nC:\\Python311\\Lib\\site-packages\\packaging\\version.py:200: InvalidVersion","steps":[{"name":"点击找好友","time":{"start":1702886410773,"stop":1702886412135,"duration":1362},"status":"broken","statusMessage":"packaging.version.InvalidVersion: Invalid version: ''\n","statusTrace":"  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\testcases\\test_home_search.py\", line 55, in test_home_search_friend\n    home_search().click_searchBox_out()\n  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\operation\\home\\home_search.py\", line 13, in click_searchBox_out\n    self.searchBox_out.click()\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 595, in click\n    el = self.get(timeout=timeout)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 523, in get\n    if not self.wait(timeout or self._global_timeout):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 559, in wait\n    if self.exists:\n       ^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 508, in exists\n    return len(self.all()) > 0\n               ^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 449, in all\n    xml_content = source or self._source or self._parent.dump_hierarchy()\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\xpath.py\", line 178, in dump_hierarchy\n    self._last_source = self._d.dump_hierarchy()\n                        ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\decorator.py\", line 232, in fun\n    return caller(func, *(extras + args), **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\retry\\api.py\", line 73, in retry_decorator\n    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\retry\\api.py\", line 33, in __retry_internal\n    return f()\n           ^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 978, in dump_hierarchy\n    content = self.jsonrpc.dumpWindowHierarchy(compressed, None)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 479, in __call__\n    return self.server._jsonrpc_retry_call(self.method, params,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 488, in _jsonrpc_retry_call\n    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 640, in reset_uiautomator\n    ok = self._force_reset_uiautomator_v2(\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 667, in _force_reset_uiautomator_v2\n    if self._is_apk_required():\n       ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 711, in _is_apk_required\n    if self._package_version(\"com.github.uiautomator.test\") is None:\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 735, in _package_version\n    return packaging.version.parse(m.group('name') if m else \"\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 54, in parse\n    return Version(version)\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"attachmentStep":false,"stepsCount":1,"hasContent":true},"afterStages":[{"name":"_xunit_setup_method_fixture_Test_home_search::0","time":{"start":1702886412458,"stop":1702886413490,"duration":1032},"status":"broken","statusMessage":"packaging.version.InvalidVersion: Invalid version: ''\n","statusTrace":"  File \"C:\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Python311\\Lib\\site-packages\\_pytest\\python.py\", line 910, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Python311\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\testcases\\test_home_search.py\", line 30, in teardown_method\n    home_search().click_cancel()\n  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\operation\\home\\home_search.py\", line 20, in click_cancel\n    self.cancel.click()\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 150, in click\n    self.must_wait(timeout=timeout)\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 344, in must_wait\n    if not self.wait(exists, timeout):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 314, in wait\n    return self.jsonrpc.waitForExists(self.selector,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 479, in __call__\n    return self.server._jsonrpc_retry_call(self.method, params,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 488, in _jsonrpc_retry_call\n    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 640, in reset_uiautomator\n    ok = self._force_reset_uiautomator_v2(\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 667, in _force_reset_uiautomator_v2\n    if self._is_apk_required():\n       ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 711, in _is_apk_required\n    if self._package_version(\"com.github.uiautomator.test\") is None:\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 735, in _package_version\n    return packaging.version.parse(m.group('name') if m else \"\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 54, in parse\n    return Version(version)\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\n","steps":[{"name":"step：点击取消","time":{"start":1702886412458,"stop":1702886413487,"duration":1029},"status":"broken","statusMessage":"packaging.version.InvalidVersion: Invalid version: ''\n","statusTrace":"  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\testcases\\test_home_search.py\", line 30, in teardown_method\n    home_search().click_cancel()\n  File \"D:\\1test\\PycharmProject1\\pycharm_ze\\CompanyProject\\APP_Forexchat\\operation\\home\\home_search.py\", line 20, in click_cancel\n    self.cancel.click()\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 150, in click\n    self.must_wait(timeout=timeout)\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 344, in must_wait\n    if not self.wait(exists, timeout):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\_selector.py\", line 314, in wait\n    return self.jsonrpc.waitForExists(self.selector,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 479, in __call__\n    return self.server._jsonrpc_retry_call(self.method, params,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 488, in _jsonrpc_retry_call\n    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 640, in reset_uiautomator\n    ok = self._force_reset_uiautomator_v2(\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 667, in _force_reset_uiautomator_v2\n    if self._is_apk_required():\n       ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 711, in _is_apk_required\n    if self._package_version(\"com.github.uiautomator.test\") is None:\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\uiautomator2\\__init__.py\", line 735, in _package_version\n    return packaging.version.parse(m.group('name') if m else \"\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 54, in parse\n    return Version(version)\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Python311\\Lib\\site-packages\\packaging\\version.py\", line 200, in __init__\n    raise InvalidVersion(f\"Invalid version: '{version}'\")\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":1,"hasContent":true},{"name":"_xunit_setup_class_fixture_Test_home_search::0","time":{"start":1702886413689,"stop":1702886414080,"duration":391},"status":"passed","steps":[{"name":"step：关闭应用","time":{"start":1702886413689,"stop":1702886414080,"duration":391},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":1,"hasContent":true}],"labels":[{"name":"epic","value":"epic:测试首页全局搜索"},{"name":"feature","value":"feature:搜索"},{"name":"tag","value":"run(order=2)"},{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_home_search"},{"name":"subSuite","value":"Test_home_search"},{"name":"host","value":"PS-03"},{"name":"thread","value":"18472-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_home_search"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["run(order=2)"]},"source":"a356b369a5cced64.json","parameterValues":[]}